## Part 1

In [30]:
pip install mysql-connector-python pandas

1600.37s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: mysql-connector-python in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (26.7.0)
Requirement already satisfied: pandas in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [34]:
import mysql.connector
 
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="qwertyuiop"   #REPLACE THIS WITH THE PASSWORD YOU SET
)
 
print(mydb)
 
if mydb.is_connected():
    print("CONNECTION SUCCESSFUL")

<mysql.connector.connection_cext.CMySQLConnection object at 0x115586540>
CONNECTION SUCCESSFUL

In [35]:
#create a database
mycursor = mydb.cursor()

mycursor.execute("CREATE DATABASE data1050f26")

In [36]:
mycursor = mydb.cursor()
mycursor.execute("SHOW DATABASES")

for x in mycursor:
  print(x)

('data1050f26',)
('information_schema',)
('mysql',)
('performance_schema',)
('sys',)

In [37]:
#create a table
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.department (dept_name VARCHAR(128) PRIMARY KEY, building VARCHAR(255), budget INT)")

In [38]:
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.student (ID VARCHAR(128) PRIMARY KEY, name VARCHAR(255), dept_name VARCHAR(128), tot_cred DECIMAL(3,2))")

In [39]:
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.instructor (ID VARCHAR(128) PRIMARY KEY, name VARCHAR(255), dept_name VARCHAR(128), salary INT)")

In [40]:
query = ('ALTER TABLE data1050f26.student ADD foreign key(dept_name) references data1050f26.department(dept_name)')
mycursor.execute(query)

In [41]:
query = ('ALTER TABLE data1050f26.instructor ADD foreign key(dept_name) references data1050f26.department(dept_name)')
mycursor.execute(query)

In [42]:
#connect to a specific database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="qwertyuiop", #REPLACE THIS WITH YOUR PASSWORD 
  database = "data1050f26" #connecting to testDatabase
)

In [43]:
mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('department',)
('instructor',)
('student',)

In [44]:
import pandas as pd

In [45]:
pip install fsspec

1659.22s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: fsspec in /Users/fumuxin/anaconda3/envs/data1050/lib/python3.12/site-packages (2026.9.0)
Note: you may need to restart the kernel to use updated packages.

In [46]:
#point the path to where in your hard drive you have stored the file department.csv
data = pd.read_csv("department.csv")

In [ ]:
for i,row in data.iterrows():
            sql = "INSERT INTO department VALUES (%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [48]:
query = "SELECT * from department"
mycursor.execute(query)

In [ ]:
for x in mycursor:
    print(x)

('AppMath', 'Pembroke', 1000525)
('CompSci', 'CIT', 4000000)
('DSI', 'Angell', 750000)
('Econ', 'Watson', 1230000)
('English', 'Litereria', 1389400)
('Math', 'Pembroke', 999785)
('Philosophy', 'Athenia', 300000)
('Psychology', 'Skinner', 1223350)
('Sociology', 'Watson', 789000)

In [50]:
#point the path to where in your hard drive you have stored the file department.csv
data = pd.read_csv("student.csv")
data.head()

     ID         name   dept_name  tot_cred
0  1238   John Smith         DSI         4
1  1645     Jane Doe  Philosophy         9
2  1888  Chuning Liu     CompSci         5
3  1970  Stan Ambani        Econ         0
4  1845    Jane Chen         DSI         2

In [51]:
data.dtypes

ID           int64
name           str
dept_name      str
tot_cred     int64
dtype: object

In [52]:
for i,row in data.iterrows():
            sql = "INSERT INTO student VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [53]:
#point the path to where in your hard drive you have stored the file department.csv
data = pd.read_csv("instructor.csv")
data.head()

    ID           name   dept_name  salary
0  111      Joe Smith         DSI  120000
1  112     Ying Zheng     CompSci  220000
2  113  Sunil Agarwal     AppMath   99000
3  114    Jennifer Lo     English   86000
4  115    Taylor Slow  Psychology   90000

In [54]:
for i,row in data.iterrows():
            sql = "INSERT INTO instructor VALUES (%s,%s,%s, %s)"
            mycursor.execute(sql, tuple(row))
            print("Record inserted")
            # the connection is not autocommitted by default, so we 
            # must commit to save our changes
            mydb.commit()

Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted
Record inserted

In [55]:
query = "SELECT * from student"
mycursor.execute(query)
for x in mycursor:
    print(x)

('1122', 'Julia Rodriguez', 'AppMath', Decimal('8.00'))
('1221', 'Ivan Petrov', 'Psychology', Decimal('9.00'))
('1238', 'John Smith', 'DSI', Decimal('4.00'))
('1298', 'Marvel Comic', 'Psychology', Decimal('6.00'))
('1333', 'Mukesh Modi', 'DSI', Decimal('7.00'))
('1444', 'Suresh Verma', 'English', Decimal('4.00'))
('1455', 'Molly Bloom', 'English', Decimal('5.00'))
('1645', 'Jane Doe', 'Philosophy', Decimal('9.00'))
('1845', 'Jane Chen', 'DSI', Decimal('2.00'))
('1881', 'Holly Zheng', 'Sociology', Decimal('5.00'))
('1888', 'Chuning Liu', 'CompSci', Decimal('5.00'))
('1934', 'Boris Pasternak', 'Math', Decimal('3.00'))
('1970', 'Stan Ambani', 'Econ', Decimal('0.00'))
('1999', 'Peter Lynch', 'AppMath', Decimal('6.00'))
('2142', 'Sabrina Zhou', 'DSI', Decimal('4.00'))
('2143', 'Maya Abdul', 'Sociology', Decimal('3.00'))
('2144', 'Karim Shiny', 'English', Decimal('5.00'))
('2145', 'Valentino Love', 'Psychology', Decimal('4.00'))
('2946', 'Steve Brown', 'Math', Decimal('9.00'))
('3303', 'Jane Lynch', 'Philosophy', Decimal('3.00'))

In [56]:
query = "SELECT * from instructor"
mycursor.execute(query)
for x in mycursor:
    print(x)

('111', 'Joe Smith', 'DSI', 120000)
('112', 'Ying Zheng', 'CompSci', 220000)
('113', 'Sunil Agarwal', 'AppMath', 99000)
('114', 'Jennifer Lo', 'English', 86000)
('115', 'Taylor Slow', 'Psychology', 90000)
('116', 'Friar Driver', 'English', 88000)
('117', 'Carmen Herman', 'DSI', 150000)
('118', 'Calista Holistic', 'CompSci', 123000)
('119', 'Rashid Irani', 'Psychology', 101000)

## Part 2

In [ ]:
# Create a table `course`
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.course (course_id VARCHAR(128) PRIMARY KEY, title VARCHAR(128), dept_name VARCHAR(128), credits INT)")

In [58]:
# add FK `dept_name`` to `course`
query = ('ALTER TABLE data1050f26.course ADD foreign key(dept_name) references data1050f26.department(dept_name)')
mycursor.execute(query)

In [ ]:
# Create a table `prereq`
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.prereq (course_id VARCHAR(128), prereq_id VARCHAR(128), PRIMARY KEY (course_id, prereq_id))")

In [ ]:
# add FK `course_id` and `prereq_id` to `prereq`
query1 = ('ALTER TABLE data1050f26.prereq ADD foreign key(course_id) references data1050f26.course(course_id)')
mycursor.execute(query1)

query2 = ('ALTER TABLE data1050f26.prereq ADD foreign key(prereq_id) references data1050f26.course(course_id)')
mycursor.execute(query2)

In [61]:
# Create a table `advisor`
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.advisor (s_id VARCHAR(128) PRIMARY KEY, i_id VARCHAR(128))")

In [62]:
# add FK `s_id` and `i_id` to `advisor`
query1 = ('ALTER TABLE data1050f26.advisor ADD foreign key(s_id) references data1050f26.student(ID)')
mycursor.execute(query1)
query2 = ('ALTER TABLE data1050f26.advisor ADD foreign key(i_id) references data1050f26.instructor(ID)')
mycursor.execute(query2)

In [63]:
# Create a table `classroom`
mycursor = mydb.cursor()
mycursor.execute("CREATE TABLE data1050f26.classroom (building VARCHAR(128), room_no VARCHAR(128), capacity INT, PRIMARY KEY (building, room_no))")

In [65]:
# Non-NULL constraint on `title` and `dept_name` in `course`
# Credits could be NULL, because some courses may not have credits (e.g., research courses, workshops, etc.)
mycursor.execute("ALTER TABLE data1050f26.course MODIFY title VARCHAR(128) NOT NULL")
mycursor.execute("ALTER TABLE data1050f26.course MODIFY dept_name VARCHAR(128) NOT NULL")

# Non-NULL constraint on `i_id` in `advisor`
mycursor.execute("ALTER TABLE data1050f26.advisor MODIFY i_id VARCHAR(128) NOT NULL")

# Non-NULL constraint on `capacity` in `classroom`
mycursor.execute("ALTER TABLE data1050f26.classroom MODIFY capacity INT NOT NULL")

In [66]:
#connect to a specific database
mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="qwertyuiop", #REPLACE THIS WITH YOUR PASSWORD 
  database = "data1050f26" #connecting to testDatabase
)

mycursor = mydb.cursor()

mycursor.execute("SHOW TABLES")

for x in mycursor:
  print(x)

('advisor',)
('classroom',)
('course',)
('department',)
('instructor',)
('prereq',)
('student',)

In [ ]:
# Show the columns (attributes, fields) of each new table
tables = ['course', 'prereq', 'advisor', 'classroom']

for table in tables:
    print(f"=== {table} ===")
    mycursor.execute(f"DESCRIBE {table}")
    for x in mycursor:
        print(x)
    print()

=== course ===
('course_id', 'varchar(128)', 'NO', 'PRI', None, '')
('title', 'varchar(128)', 'NO', '', None, '')
('dept_name', 'varchar(128)', 'NO', 'MUL', None, '')
('credits', 'int', 'YES', '', None, '')

=== prereq ===
('course_id', 'varchar(128)', 'NO', 'PRI', None, '')
('prereq_id', 'varchar(128)', 'NO', 'PRI', None, '')

=== advisor ===
('s_id', 'varchar(128)', 'NO', 'PRI', None, '')
('i_id', 'varchar(128)', 'NO', 'MUL', None, '')

=== classroom ===
('building', 'varchar(128)', 'NO', 'PRI', None, '')
('room_no', 'varchar(128)', 'NO', 'PRI', None, '')
('capacity', 'int', 'NO', '', None, '')

## Part 3

In [76]:
# Populate the `course` table with data from `course.csv`
data = pd.read_csv("course.csv")
for i,row in data.iterrows():
            sql = "INSERT INTO course VALUES (%s,%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            mydb.commit()

In [77]:
# Populate the `prereq` table with data from `prereq.csv`
data = pd.read_csv("prereq.csv")
for i,row in data.iterrows():
            sql = "INSERT INTO prereq VALUES (%s,%s)"
            mycursor.execute(sql, tuple(row))
            mydb.commit()

In [78]:
# Populate the `advisor` table with data from `advisor.csv`
data = pd.read_csv("advisor.csv")
for i,row in data.iterrows():
            sql = "INSERT INTO advisor VALUES (%s,%s)"
            mycursor.execute(sql, tuple(row))
            mydb.commit()

In [79]:
# Populate the `classroom` table with data from `advisor.csv`
data = pd.read_csv("classroom.csv")
for i,row in data.iterrows():
            sql = "INSERT INTO classroom VALUES (%s,%s,%s)"
            mycursor.execute(sql, tuple(row))
            mydb.commit()

In [80]:
tables = ['department', 'student', 'instructor', 'course', 'prereq', 'advisor', 'classroom']

for table in tables:
    print(f"=== {table} ===")
    mycursor.execute(f"SELECT * FROM {table} LIMIT 5")
    for x in mycursor:
        print(x)
    print()

=== department ===
('AppMath', 'Pembroke', 1000525)
('CompSci', 'CIT', 4000000)
('DSI', 'Angell', 750000)
('Econ', 'Watson', 1230000)
('English', 'Litereria', 1389400)

=== student ===
('1122', 'Julia Rodriguez', 'AppMath', Decimal('8.00'))
('1221', 'Ivan Petrov', 'Psychology', Decimal('9.00'))
('1238', 'John Smith', 'DSI', Decimal('4.00'))
('1298', 'Marvel Comic', 'Psychology', Decimal('6.00'))
('1333', 'Mukesh Modi', 'DSI', Decimal('7.00'))

=== instructor ===
('111', 'Joe Smith', 'DSI', 120000)
('112', 'Ying Zheng', 'CompSci', 220000)
('113', 'Sunil Agarwal', 'AppMath', 99000)
('114', 'Jennifer Lo', 'English', 86000)
('115', 'Taylor Slow', 'Psychology', 90000)

=== course ===
('APMA1650', 'Statistical Inference 1', 'AppMath', 1)
('CSCI1270', 'Database Management Systems', 'CompSci', 1)
('Data1030', 'Hands-on data science', 'DSI', 1)
('Data1050', 'Data Engineering', 'DSI', 1)
('Data1450', 'Text Analysis', 'DSI', 1)

=== prereq ===
('Data1050', 'CSCI1270')
('Data2050', 'Data1030')
('Data1030', 'Data1050')
('Data2050', 'Data1050')
('Econ9999', 'Econ2180')

=== advisor ===
('1238', '111')
('1333', '111')
('1845', '111')
('2142', '111')
('1970', '113')

=== classroom ===
('Angell', '303', 80)
('Angell', '370', 20)
('Angell', '405', 30)
('CIT', '312', 200)
('CIT', '320', 55)